In [1]:
import numpy as np

## DataTypes & Attributes

In [2]:
# NumPy's main datatypy is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [7]:
a2 = np.array([[1, 2.0, 3.3],
              [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3], 
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [8]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [9]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [10]:
a1.shape

(3,)

In [12]:
a2.shape

(2, 3)

In [15]:
a3.shape

(2, 3, 3)

In [18]:
a1

array([1, 2, 3])

In [19]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [20]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [14]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [21]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [22]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [23]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [25]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating arrays

In [26]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [27]:
sample_array.dtype

dtype('int32')

In [28]:
ones = np.ones((2,3))

In [29]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [30]:
ones.dtype

dtype('float64')

In [31]:
type(ones)

numpy.ndarray

In [34]:
zeros = np.zeros((2,3))

In [35]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [37]:
range_array = np.arange(0, 10, 2)

In [38]:
range_array

array([0, 2, 4, 6, 8])

In [41]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[5, 6, 3, 6, 6],
       [7, 6, 5, 7, 8],
       [7, 1, 4, 9, 6]])

In [43]:
random_array.size

15

In [44]:
random_array.shape

(3, 5)

In [52]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.51270727, 0.37219509, 0.69007409],
       [0.76215987, 0.75589543, 0.46476117],
       [0.11591365, 0.83533294, 0.63903783],
       [0.75882353, 0.27704257, 0.34167779],
       [0.69228581, 0.71644001, 0.90616953]])

In [47]:
random_array.shape

(3, 5)

In [50]:
random_array_3 = np.random.rand(5, 3)

In [51]:
random_array_3

array([[0.71396056, 0.65377367, 0.63710738],
       [0.63443033, 0.82631808, 0.81287686],
       [0.58095489, 0.07879005, 0.36023905],
       [0.63352019, 0.81503353, 0.1804457 ],
       [0.80792856, 0.5710762 , 0.18194831]])

In [66]:
# Pseudo-random_numbers
np.random.seed(seed=99999)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

In [84]:
np.random.seed(7)
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [82]:
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.80047905, 0.93911135, 0.04065581],
       [0.87567172, 0.27656307, 0.4757645 ],
       [0.79676096, 0.71724223, 0.14714757],
       [0.65874826, 0.06925207, 0.35707063],
       [0.81282955, 0.42770483, 0.59985444]])

In [73]:
random_array_4.shape

(5, 3)

## 3. Viewing arrays and matrics

In [87]:
np.unique(random_array_4)

array([0, 1, 3, 4, 5, 6, 8, 9])

In [88]:
a1

array([1, 2, 3])

In [89]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [90]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [91]:
a1[0]

1

In [94]:
a2.shape

(2, 3)

In [95]:
a2[0]

array([1. , 2. , 3.3])

In [100]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [97]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [101]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [102]:
a2[1]

array([4. , 5. , 6.5])

In [103]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [106]:
a3.shape

(2, 3, 3)

In [104]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [109]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[0, 5, 3, 0, 5],
         [7, 1, 8, 4, 9],
         [0, 2, 0, 7, 6],
         [2, 9, 9, 5, 1]],

        [[0, 0, 9, 1, 1],
         [5, 3, 2, 0, 4],
         [8, 7, 1, 4, 9],
         [3, 6, 7, 1, 0]],

        [[2, 7, 0, 0, 9],
         [8, 2, 0, 5, 5],
         [0, 9, 0, 8, 4],
         [5, 1, 4, 0, 7]]],


       [[[2, 0, 3, 9, 8],
         [3, 7, 1, 0, 1],
         [4, 6, 1, 0, 1],
         [0, 1, 8, 4, 1]],

        [[6, 8, 5, 2, 4],
         [7, 4, 1, 2, 8],
         [5, 2, 9, 6, 2],
         [5, 7, 7, 5, 5]],

        [[6, 0, 6, 4, 6],
         [2, 6, 8, 7, 0],
         [5, 8, 9, 7, 7],
         [6, 2, 5, 6, 1]]]])

In [112]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [117]:
# Get the first 4 numbers of the inner most arrays
a4[:, :, :, :1]

array([[[[0],
         [7],
         [0],
         [2]],

        [[0],
         [5],
         [8],
         [3]],

        [[2],
         [8],
         [0],
         [5]]],


       [[[2],
         [3],
         [4],
         [0]],

        [[6],
         [7],
         [5],
         [5]],

        [[6],
         [2],
         [5],
         [6]]]])