# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [5]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [6]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1, 2, 3])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1, 2.0, 3.3],
              [4, 5, 6.5]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1, 2, 3], 
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]],
               [[19, 20, 21],
                [22, 23, 24],
                [25, 26, 27]]])
a3.shape

(3, 3, 3)

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [8]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [9]:
# Attributes of 2-dimensional array
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('float64'), 6, numpy.ndarray)

In [10]:
# Attributes of 3-dimensional array
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((3, 3, 3), 3, dtype('int32'), 27, numpy.ndarray)

In [11]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [13]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [17]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((10,2))
zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [18]:
# Create an array within a range of 0 and 100 with step 3
range_array = np.arange(0, 10, 3)
range_array

array([0, 3, 6, 9])

In [19]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array = np.random.randint(0, 10, size=(7, 2))
random_array

array([[1, 5],
       [1, 9],
       [5, 2],
       [7, 2],
       [1, 0],
       [6, 2],
       [6, 3]])

In [30]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_array_2 = np.random.uniform(0, 1, size=(3,5))
random_array_2

array([[0.56826249, 0.02515751, 0.25453909, 0.30771228, 0.25178745],
       [0.58372184, 0.55162053, 0.74972376, 0.86167673, 0.65235307],
       [0.62366733, 0.03717249, 0.5623043 , 0.21881205, 0.88961049]])

In [39]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array_3 = np.random.randint(0, 10, size=(4,6))
random_array_3

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [41]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_array_4 = np.random.randint(1, 10, size=(3,7))
random_array_4

# Find the unique numbers in the array you just created
np.unique(random_array_4)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
# Find the 0'th index of the latest array you created
random_array_4[0]

array([7, 8, 3, 1, 4, 2, 8])

In [44]:
# Get the first 2 rows of latest array you created
random_array_4[:2]

array([[7, 8, 3, 1, 4, 2, 8],
       [4, 2, 6, 6, 4, 6, 2]])

In [102]:
# Get the first 2 values of the first 2 rows of the latest array
random_array_4[:2, :2]

array([[7, 8],
       [4, 2]])

In [103]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_array_5 = np.random.randint(0, 10, size=(3,5))
ones_2 = np.ones((3,5))
random_array_5, ones_2

(array([[2, 5, 1, 9, 8],
        [4, 5, 3, 9, 6],
        [8, 6, 0, 0, 8]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [104]:
# Add the two arrays together
sum_1 = random_array_5 + ones_2
sum_1

array([[ 3.,  6.,  2., 10.,  9.],
       [ 5.,  6.,  4., 10.,  7.],
       [ 9.,  7.,  1.,  1.,  9.]])

In [105]:
# Create another array of ones of shape (5, 3)
ones_3 = np.ones((5,3))
ones_3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [106]:
# Try add the array of ones and the other most recent array together
sum_1 + ones_3.T

array([[ 4.,  7.,  3., 11., 10.],
       [ 6.,  7.,  5., 11.,  8.],
       [10.,  8.,  2.,  2., 10.]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [107]:
# Create another array of ones of shape (3, 5)
ones_4 = np.ones((3,5))
ones_4

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [108]:
# Subtract the new array of ones from the other most recent array
sum_1 - ones_4

array([[2., 5., 1., 9., 8.],
       [4., 5., 3., 9., 6.],
       [8., 6., 0., 0., 8.]])

In [109]:
# Multiply the ones array with the latest array
sum_1 * ones_4

array([[ 3.,  6.,  2., 10.,  9.],
       [ 5.,  6.,  4., 10.,  7.],
       [ 9.,  7.,  1.,  1.,  9.]])

In [110]:
# Take the latest array to the power of 2 using '**'
sum_1 ** 2

array([[  9.,  36.,   4., 100.,  81.],
       [ 25.,  36.,  16., 100.,  49.],
       [ 81.,  49.,   1.,   1.,  81.]])

In [111]:
# Do the same thing with np.square()
np.square(sum_1)

array([[  9.,  36.,   4., 100.,  81.],
       [ 25.,  36.,  16., 100.,  49.],
       [ 81.,  49.,   1.,   1.,  81.]])

In [112]:
# Find the mean of the latest array using np.mean()
np.mean(sum_1)

5.933333333333334

In [113]:
# Find the maximum of the latest array using np.max()
np.max(sum_1)

10.0

In [114]:
# Find the minimum of the latest array using np.min()
np.min(sum_1)

1.0

In [116]:
# Find the standard deviation of the latest array
np.std(sum_1)

3.0652170486860397

In [117]:
# Find the variance of the latest array
np.var(sum_1)

9.395555555555555

In [118]:
# Reshape the latest array to (3, 5, 1)
sum_1.reshape(3, 5, 1)

array([[[ 3.],
        [ 6.],
        [ 2.],
        [10.],
        [ 9.]],

       [[ 5.],
        [ 6.],
        [ 4.],
        [10.],
        [ 7.]],

       [[ 9.],
        [ 7.],
        [ 1.],
        [ 1.],
        [ 9.]]])

In [120]:
# Transpose the latest array
sum_1.T

array([[ 3.,  5.,  9.],
       [ 6.,  6.,  7.],
       [ 2.,  4.,  1.],
       [10., 10.,  1.],
       [ 9.,  7.,  9.]])

What does the transpose do?

In [128]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
rand_int_1 = np.random.randint(0, 10, size=(3,3))
rand_int_2 = np.random.randint(0, 10, size=(3,2))
rand_int_1, rand_int_2

(array([[2, 3, 6],
        [3, 8, 0],
        [7, 6, 1]]),
 array([[7, 0],
        [8, 8],
        [1, 6]]))

In [129]:
# Perform a dot product on the two newest arrays you created
np.dot(rand_int_1, rand_int_2)

array([[44, 60],
       [85, 64],
       [98, 54]])

In [125]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
rand_int_3 = np.random.randint(0, 10, size=(4,3))
rand_int_4 = np.random.randint(0, 10, size=(4,3))
rand_int_3, rand_int_4

(array([[4, 9, 5],
        [6, 3, 6],
        [7, 0, 5],
        [7, 4, 3]]),
 array([[1, 5, 5],
        [0, 8, 5],
        [2, 3, 3],
        [2, 9, 2]]))

In [126]:
# Perform a dot product on the two newest arrays you created
np.dot(rand_int_3, rand_int_4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [127]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(rand_int_3, rand_int_4.T)

array([[74, 97, 50, 99],
       [51, 54, 39, 51],
       [32, 25, 29, 24],
       [42, 47, 35, 56]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [144]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
rand_int_5 = np.random.randint(0, 10, size=(3,3))
rand_int_6 = np.random.randint(0, 10, size=(3,3))
rand_int_5, rand_int_6

(array([[0, 1, 0],
        [4, 4, 6],
        [8, 8, 2]]),
 array([[2, 2, 3],
        [7, 5, 7],
        [0, 7, 3]]))

In [145]:
# Compare the two arrays with '>'
rand_int_5 > rand_int_6

array([[False, False, False],
       [False, False, False],
       [ True,  True, False]])

What happens when you compare the arrays with `>`?

In [146]:
# Compare the two arrays with '>='
rand_int_5 >= rand_int_6

array([[False, False, False],
       [False, False, False],
       [ True,  True, False]])

In [147]:
# Find which elements of the first array are greater than 7
rand_int_5 > 7

array([[False, False, False],
       [False, False, False],
       [ True,  True, False]])

In [148]:
# Which parts of each array are equal? (try using '==')
rand_int_5 == rand_int_6

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [151]:
# Sort one of the arrays you just created in ascending order
np.sort(rand_int_5)

array([[0, 0, 1],
       [4, 4, 6],
       [2, 8, 8]])

In [152]:
# Sort the indexes of one of the arrays you just created
np.argsort(rand_int_5)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [153]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(rand_int_5)

7

In [154]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(rand_int_5)

0

In [155]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(rand_int_5, axis=1)

array([2, 2, 1], dtype=int64)

In [156]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(rand_int_5, axis=0)

array([0, 0, 0], dtype=int64)

In [159]:
# Create an array of normally distributed random numbers
result_1 = np.random.uniform(0, 10, size=(3,5))
result_1

array([[8.98554189, 6.0642906 , 0.09197052, 1.01471543, 6.63501769],
       [0.05061584, 1.60808051, 5.48733789, 6.91895198, 6.5196126 ],
       [2.24269309, 7.12179221, 2.37249087, 3.25399698, 7.46491405]])

In [169]:
# Create an array with 10 evenly spaced numbers between 1 and 100
result_2 = np.linspace(1, 100, num=10)
result_2

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.